name: LaTeX Build Check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu を使用
    container: aruneko/texlive  # TeXLive の環境を構築

    steps:
    # 1. リポジトリのコードを取得
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. LaTeX 文書をコンパイル
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        latexmk_use_lualatex: true
